---
- name: Loop Register Test
  gather_facts: no
  hosts: localhost
  tasks:
    - name: Looping Echo Task
      shell: "echo This is my item: {{ item }}"
      loop:
        - one
        - two
      register: output
    - debug: var=output['results']
      #   msg: "{{ item['stdout'] }}"
      # loop: "{{ output['results'] }}"
