- name: 모든 서버 셧다운
  hosts: ansibles
  tasks:
  - name: ansible1 ~ ansible4 서버 셧다운
    reboot:
      reboot_timeout: 10

- name: 현재 서버 셧다운
  hosts: localmachine
  tasks:
  - name: ansible 서버 셧다운
    reboot:
      reboot_timeout: 20
