---
- name: 패키지 삭제 예제
  hosts: lamp
  vars:
    firewall: firewalld
  tasks:
  - name: 변수 포함(Include the variable file)
    include_vars: vars/main.yml

  - name: "{{ web_root }}/index.html 파일 삭제"
    file:
      path: "{{ web_root }}/index.html"
      state: absent

  - name: 방화벽에 웹서비스 공개(expose)
    firewalld:
      service: http
      permanent: yes
      immediate:  yes
      state: disabled

  - name: DB 서비스 종료
    service:
      name: "{{ item }}" 
      state: stopped
      enabled: no
    with_items:
    - "{{ ansible_local.custom.services.db_service }}"
    - "{{ ansible_local.custom.services.web_service }}"

  - name: 웹서버 & DB서버 패키지 삭제
    yum:
      name: 
        - "{{ ansible_local.custom.packages.db_package }}"
        - "{{ ansible_local.custom.packages.web_package }}"
      state: absent
