---
- name: Task Failure Exercise
  hosts: databases
  vars:
    web_package: http     # 잘못된 정보 그대로 입력
    db_package: mariadb-server
    db_servcie: mariadb
  tasks:
    - name: Install {{ web_package }} package
      yum:
        name: "{{ web_package }}"
        state: present

    - name: Install {{ db_package }} package
      yum:
        name: "{{ db_package }}"
        state: present
