---
- name: Task Failure Exercise 실습 정리 작업
  hosts: all
  vars:
    web_package: httpd     # 잘못된 정보 그대로 입력
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Stop the {{ db_service }} service
      service:
        name: "{{ db_service }}"
        state: stopped

    - name: Uninstall the {{ web_package }} package
      yum:
        name: "{{ web_package }}"
        state: absent

    - name: Uninstall the {{ db_package }} package
      yum:
        name: "{{ db_package }}"
        state: absent
