---
# 1) 방화벽 서비스 OFF - http(80/tcp), https(443/tcp) => firewalld
# 2) 서비스 OFF - httpd => service
# 3) 서비스 설정 삭제 - /var/www/html/index.html => file
# 4) 패키지 삭제 - httpd, mod_ssl => yum

- name: "인트라넷 웹서버 설정 복원 작업"
  hosts: web1
  gather_facts: no
  tasks:
    # 1) 패키지 삭제 - httpd
    - name: "패키지 삭제 - httpd"
      ansible.builtin.yum:
        name: httpd
        state: absent

    # 2) 파일 삭제 - /var/www/html/index.html
    - name: "파일 삭제 - /var/www/html/index.html"
      ansible.builtin.file: 
        path: /var/www/html/index.html
        state: absent

    # 3) 방화벽 포트 닫기 - http, https
    - name: "방화벽 포트 닫기 - http, https"
      ansible.builtin.firewalld:
        service: "{{ item }}"
        state: disabled
        permanent: yes
        immediate: yes
      loop:
      - http
      - https
